apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: moodride
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.moodride.svc.cluster.local:9092
  SPRING_REDIS_HOST: redis.moodride.svc.cluster.local
  SPRING_REDIS_PORT: "6379"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus

