apiVersion: v1
kind: Service
metadata:
  name: route-api
  namespace: moodride
  labels:
    app: route-api
spec:
  selector:
    app: route-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080

