apiVersion: v1
kind: Service
metadata:
  name: route-worker
  namespace: moodride
  labels:
    app: route-worker
spec:
  selector:
    app: route-worker
  ports:
    - name: http
      port: 8081
      targetPort: 8081

